#### Creating Dataframe object for the jobs that need to be scheduled

In [8]:
import pandas as pd

jobs_data = {
    "jobs": ["A", "B", "C", "D", "E"],
    "arrival_time": [0, 1, 2, 3, 4],
    "processing_time": [11, 29, 31, 1, 2],
    "due_date": [61, 45, 31, 33, 32]
}

df = pd.DataFrame(jobs_data)

  jobs  arrival_time  processing_time  due_date
0    A             0               11        61
1    B             1               29        45
2    C             2               31        31
3    D             3                1        33
4    E             4                2        32

#### First Come First Serve Dynamic Job Scheduling

In [48]:
# Sorting jobs received as per there arrival time
df_sorted = df.sort_values(by='arrival_time')
df_sorted

  jobs  arrival_time  processing_time  due_date
0    A             0               11        61
1    B             1               29        45
2    C             2               31        31
3    D             3                1        33
4    E             4                2        32

In [54]:
# Finish Time, Flow Time(Finish Time - Arrival Time), Tardiness(max(Finish Time - Due Date, 0))
df_sorted["finish_time"] = None
df_sorted["flow_time"] = None
df_sorted["tardiness"] = None

current_time = 0

# Iterating over the received jobs as per first come first serve jobs
for index, row in df_sorted.iterrows():
    finish_time = current_time + row.processing_time

    # Updating data in the dataframe for the calculated values
    df_sorted.loc[index, "finish_time"] = finish_time
    df_sorted.loc[index, "flow_time"] = finish_time - row.arrival_time
    df_sorted.loc[index, "tardiness"] = max(finish_time - row.due_date, 0)

    # Updating current time with the finish time of the current job
    current_time = finish_time

    # DEBUG LOG: Uncomment this line to see logs
    # print(f"Index: {index}, Job: {row.jobs}, Arrival Time: {row.arrival_time}, Finish time: {finish_time}, Flow time: {finish_time - row.arrival_time}")

In [55]:
df_sorted

,jobs,arrival_time,processing_time,due_date,finish_time,flow_time,tardiness
0,A,0,11,61,11,11,0
1,B,1,29,45,40,39,0
2,C,2,31,31,71,69,40
3,D,3,1,33,72,69,39
4,E,4,2,32,74,70,42

In [56]:
avg_tardiness = df_sorted['tardiness'].mean()
avg_flow_time = df_sorted['flow_time'].mean()

In [46]:
print(f"Avg Tardiness: {avg_tardiness}, Avg Flow time: {avg_flow_time}")

Avg Tardiness: 24.2, Avg Flow time: 51.6